### ISSUE TITLE
Please read: some history for maintainers

### ISSUE THREAD

**Issue by pelson** [conda-forge/pyzmq-feedstock#1]
The development of this feedstock was done in https://github.com/conda-forge/staged-recipes/pull/292 where a number of issues were found on OSX and Windows. 

**The good news:** if you change something it will likely be picked up by failures in the CI.
**The bad news:** the changes are really subtle.

**Comment by minrk** [comment]
Thanks for enduring that learning experience!

**Comment by pelson** [comment]
We have binaries in https://anaconda.org/conda-forge/pyzmq/files.

**Comment by minrk** [comment]
I think things have stabilized and matured a fair amount here, so we don't need to keep this open.
