### ISSUE TITLE
Tagging packages on conda-forge

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/pyzmq-feedstock#27]
cc @ocefpaf @jakirkham @pelson @minrk @JohanMabille @scottdraves @conda-forge/core 

There is a bug that might require removing / tagging packages from the conda-forge channel.

Here is the gist of it:

- The conda package for `pyzmq 16.0.2` builds 1 and 2 required `zeromq 4.2*`, which was wrong since it is linking explicitly with `zeromq 4.2.1`, which was the only version satisfying `4.2*` so far.
- We just released `zeromq 4.2.3` and noticed the bug.
- We made a new build for `pyzmq 16.0.2` (build 3) pinning `zeromq` to `4.2.1`.
- However, `conda install pyzmq -c conda-forge` still gets us `pyzmq 16.0.2-2` and `zeromq 4.2.3`.

So we probably need to tag builds 0, 1 and 2 of pyzmq 16.0.2 as broken. This is true for both OSX and Linux.

**Comment by scottdraves** [comment]
you mean `conda install -c conda-forge pyzmq`?

**Comment by SylvainCorlay** [comment]
> you mean conda install -c conda-forge pyzmq?

Right, edited.

**Comment by jakirkham** [comment]
Marked `pyzmq 16.0.2` builds `1` and `2` as `broken`. Is that what you were looking for? Were there others that need to be marked? Can you please check that I got all of them?

**Comment by SylvainCorlay** [comment]
thanks, I am checking the list.

**Comment by SylvainCorlay** [comment]
This looks all ok. I am testing installation on both OS X and Linux.

**Comment by SylvainCorlay** [comment]
I am getting the right versions of pyzmq and zeromq on both linux and OS X.

I am testing an installation of Jupyter as a quick last check.

Thank you @jakirkham and @ocefpaf.

**Comment by scottdraves** [comment]
worked for me

**Comment by minrk** [comment]
Thanks for fixing this! It's probably a result of a bug in libzmq, because upgrading libzmq patch version shouldn't break pyzmq. On macOS, this is usually the fault of setting `install_name` incorrectly to `libzmq.5.1.1.dylib` instead of `libzmq.dylib` or `libzmq.5.dylib`. ABI versions are specifically there to avoid this kind of breakage. I'm not certain what the linux equivalent is.
