### ISSUE TITLE
build zeromq with older machine?

### ISSUE THREAD

**Issue by hainm** [conda-forge/pyzmq-feedstock#7]
Hi,

I normally use jupyter notebook + ipywidget from anaconda distribution. I've just created a fresh
conda env to try ipywidget 5.1.5. I was trying to open the notebook but got ABI error.

`ImportError: /home/haichit/anaconda3/envs/py35_ipywidgets5/lib/python3.5/site-packages/zmq/backend/cython/../../../../../libzmq.so.5: ELF file OS ABI invalid`

The computer cluster I am using is CentOS 5.6

Is it possible to fix that? 

PS: a work around is `conda install zeromq` to use `zeromq` from anaconda channel.

**Comment by jakirkham** [comment]
We don't support CentOS 5. Everything here is built for CentOS 6.

**Comment by hainm** [comment]
hi. can you point me to the link discussing CentOS 5 and 6? thanks.

**Comment by jakirkham** [comment]
There's not really one thread where this is discussed, but it was discussed in a variety of threads. The closest thread I can give you is this compiler thread ( https://github.com/conda-forge/conda-forge.github.io/issues/29 ). Ultimately this got resolved in a conference call.

We were already using CentOS 6 for awhile and simply decided we were not switching to CentOS 5. This has to do with issues trying to build certain things, lack of support for a variety of software, CentOS 5 rapidly approaching [EOL]( https://wiki.centos.org/FAQ/CentOS5#head-a2fd35a09ebf776661ab0f1288762329bb64209c ), and time spent rebuilding everything on CentOS 5. Given how rarely we hear about a need for CentOS 5 and the aforementioned problems, it is doubtful that this will change.

**Comment by hainm** [comment]
thanks for the pointer.

**Comment by jakirkham** [comment]
Sure. Sorry this is causing you issues. Is there some reason that the cluster in question is not being upgraded to CentOS 6?

**Comment by hainm** [comment]
> Is there some reason that the cluster in question is not being upgraded to CentOS 6?

I have not asked that. It's computer cluster in our lab and no one seems complaining about centos 5, so I guess there is no need to upgrade.

btw, I think I can use both `conda-forge` and official anaconda channel for now. thanks.

**Comment by jakirkham** [comment]
Definitely, make sure to raise this EOL point to the right people in your lab. They really should be made aware of this.

I know `anaconda` tries to keep compatibility with CentOS 5. Not sure when they plan to drop that though.
